% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={M05 Initial Models Report - County Childhood Vaccination Uptake},
  pdfauthor={Geoffrey Bruder},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{M05 Initial Models Report - County Childhood Vaccination Uptake}
\author{Geoffrey Bruder}
\date{April 09, 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\newpage

\section{Title Page}\label{title-page}

\textbf{Project title:} County Childhood Vaccination Uptake --- Initial
Models Report\\
\textbf{Author:} Geoffrey Bruder\\
\textbf{Date:} April 09, 2026

\newpage

\section{Executive summary}\label{executive-summary}

\begin{itemize}
\tightlist
\item
  \textbf{Target:} county-level MMR completion (19--35 months).\\
\item
  \textbf{Baseline model:} Random Forest (ranger). Held-out RMSE ≈
  \textbf{TBD} percentage points.\\
\item
  \textbf{Top predictors (baseline):} median household income and
  broadband access (per permutation importance ranking).\\
\item
  \textbf{Key limitations:} ecological inference, measurement error in
  survey-derived hesitancy, and spatial autocorrelation in residuals
  (Breusch-Pagan p reported below indicates heteroskedasticity).\\
\item
  \textbf{Next steps:} run nested CV tuning, compute SHAP/PDP for top
  predictors, test spatial autocorrelation (Moran's I), and report
  standardized effect sizes from Elastic Net.
\end{itemize}

\newpage

\section{Background and question
(recap)}\label{background-and-question-recap}

This report documents initial model fitting for county-level MMR
completion (19-35 months). The research question:

\textbf{Which county-level sociodemographic and survey-derived
indicators best explain variation in MMR completion across U.S.
counties?}

Working hypothesis: higher broadband access, higher median household
income, and higher educational attainment are associated with higher MMR
completion; higher local vaccine hesitancy is associated with lower
completion.

\newpage

\section{Data and reproducibility
(short)}\label{data-and-reproducibility-short}

This analysis expects a canonical input file produced by the
harmonization notebook:

\begin{itemize}
\tightlist
\item
  \texttt{data\_clean/analysis\_table.csv} --- required columns:
  \textbf{fips} (5-character string), \textbf{coverage\_estimate}
  (numeric), \textbf{median\_household\_income} (numeric),
  \textbf{pct\_broadband\_households} (numeric),
  \textbf{count\_bachelors\_plus} (numeric),
  \textbf{delphi\_vax\_hesitancy} (numeric). Optional:
  \texttt{pct\_white}, \texttt{pct\_black}, \texttt{pct\_native}.\\
\item
  \texttt{data\_clean/county\_centroids.csv} (optional) --- columns:
  \texttt{fips}, \texttt{lon}, \texttt{lat} for spatial checks.
\end{itemize}

All saved artifacts are written to \texttt{models/} and include
timestamps. The full ingestion and harmonization code is available in
the Appendix for reproducibility.

\newpage

\section{Methods (concise, technical)}\label{methods-concise-technical}

\textbf{Algorithm selection.} Baseline: Random Forest (ranger via
parsnip). Rationale: captures nonlinearities and interactions, robust to
monotonic transforms and moderate outliers, and supports permutation
importance.

\textbf{Benchmark plan.} Compare Random Forest to Elastic Net (glmnet)
and gradient boosting. Selection via nested cross-validation minimizing
mean CV RMSE; final evaluation on held-out test set.

\textbf{Validation strategy.} 80/20 holdout split; 5-fold CV on training
for baseline; nested CV for tuning (template provided in Appendix).

\newpage

\section{Prepare data and preprocessing (visible outputs
only)}\label{prepare-data-and-preprocessing-visible-outputs-only}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{analysis\_path }\OtherTok{\textless{}{-}} \FunctionTok{file.path}\NormalTok{(}\StringTok{"data\_clean"}\NormalTok{, }\StringTok{"analysis\_table.csv"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{file.exists}\NormalTok{(analysis\_path)) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"**Note:** analysis\_table.csv not found. The synthetic demo will be used for knitting. See Appendix for full ingestion code.}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{  n }\OtherTok{\textless{}{-}} \DecValTok{200}
  \FunctionTok{set.seed}\NormalTok{(}\DecValTok{2026}\NormalTok{)}
\NormalTok{  analysis }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}
    \AttributeTok{fips =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%05d"}\NormalTok{, }\DecValTok{1000} \SpecialCharTok{+} \FunctionTok{seq\_len}\NormalTok{(n)),}
    \AttributeTok{coverage\_estimate =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{95}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{pct\_broadband\_households =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{40}\NormalTok{, }\DecValTok{95}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{median\_household\_income =} \FunctionTok{sample}\NormalTok{(}\FunctionTok{seq}\NormalTok{(}\DecValTok{21500}\NormalTok{, }\DecValTok{103576}\NormalTok{, }\AttributeTok{by =} \DecValTok{100}\NormalTok{), n, }\AttributeTok{replace =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{count\_bachelors\_plus =} \FunctionTok{sample}\NormalTok{(}\DecValTok{121}\SpecialCharTok{:}\DecValTok{4903}\NormalTok{, n, }\AttributeTok{replace =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{pct\_white =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{30}\NormalTok{, }\DecValTok{95}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{pct\_black =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{50}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{pct\_native =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{5}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{delphi\_vax\_hesitancy =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\FloatTok{0.005}\NormalTok{, }\FloatTok{0.999}\NormalTok{), }\DecValTok{3}\NormalTok{)}
\NormalTok{  )}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  analysis }\OtherTok{\textless{}{-}}\NormalTok{ readr}\SpecialCharTok{::}\FunctionTok{read\_csv}\NormalTok{(analysis\_path, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{  analysis }\OtherTok{\textless{}{-}}\NormalTok{ analysis }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =} \FunctionTok{as.character}\NormalTok{(fips),}
           \AttributeTok{coverage\_estimate =} \FunctionTok{as.numeric}\NormalTok{(coverage\_estimate),}
           \AttributeTok{pct\_broadband\_households =} \FunctionTok{as.numeric}\NormalTok{(pct\_broadband\_households),}
           \AttributeTok{median\_household\_income =} \FunctionTok{as.numeric}\NormalTok{(median\_household\_income),}
           \AttributeTok{count\_bachelors\_plus =} \FunctionTok{as.numeric}\NormalTok{(count\_bachelors\_plus),}
           \AttributeTok{delphi\_vax\_hesitancy =} \FunctionTok{as.numeric}\NormalTok{(delphi\_vax\_hesitancy))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{Note:} analysis\_table.csv not found. The synthetic demo will be
used for knitting. See Appendix for full ingestion code.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{required\_cols }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"fips"}\NormalTok{,}\StringTok{"coverage\_estimate"}\NormalTok{,}\StringTok{"median\_household\_income"}\NormalTok{,}\StringTok{"pct\_broadband\_households"}\NormalTok{,}\StringTok{"count\_bachelors\_plus"}\NormalTok{,}\StringTok{"delphi\_vax\_hesitancy"}\NormalTok{)}
\NormalTok{missing\_cols }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(required\_cols, }\FunctionTok{names}\NormalTok{(analysis))}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(missing\_cols)) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"**Missing required columns:**"}\NormalTok{, }\FunctionTok{paste}\NormalTok{(missing\_cols, }\AttributeTok{collapse =} \StringTok{", "}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"**Schema validated:** all required columns present.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{Schema validated:} all required columns present.

\textbf{Interpretation:} The dataset schema is validated. If any
required columns are missing, the pipeline will not proceed; see
Appendix for harmonization steps.

\newpage

\section{Split, preprocessing, and exported artifacts
(concise)}\label{split-preprocessing-and-exported-artifacts-concise}

\begin{longtable}[t]{lrr}
\caption{\label{tab:split-and-prep}Table: Split diagnostics (counts and mean coverage by partition)}\\
\toprule
set & n & mean\_coverage\\
\midrule
train & 160 & 70.304\\
test & 40 & 70.899\\
\bottomrule
\end{longtable}

\textbf{Caption (split diagnostics):} Training partition: 160 counties,
mean coverage 70.304 percentage points. Held-out test partition: 40
counties, mean coverage 70.899 percentage points.

\newpage

\section{Baseline Random Forest: fit and held-out evaluation
(results)}\label{baseline-random-forest-fit-and-held-out-evaluation-results}

\begin{longtable}[t]{llr}
\caption{\label{tab:rf-fit-visible}Table: Held-out test set performance metrics (baseline Random Forest)}\\
\toprule
.metric & .estimator & .estimate\\
\midrule
rmse & standard & 13.224611\\
rsq & standard & 0.000477\\
mae & standard & 11.158634\\
\bottomrule
\end{longtable}

\textbf{Caption (held-out metrics):} Held-out RMSE = 13.225 percentage
points; R\^{}2 = \ensuremath{4.77\times 10^{-4}}. Interpret RMSE in
absolute percentage-point terms for policy relevance.

\newpage

\section{Cross-validation summary
(training)}\label{cross-validation-summary-training}

\begin{longtable}[t]{llrrrl}
\caption{\label{tab:cv-visible}Table: 5-fold cross-validated performance (training set)}\\
\toprule
.metric & .estimator & mean & n & std\_err & .config\\
\midrule
rmse & standard & 13.9142640 & 5 & 0.1967364 & pre0\_mod0\_post0\\
rsq & standard & 0.0353617 & 5 & 0.0258590 & pre0\_mod0\_post0\\
\bottomrule
\end{longtable}

\textbf{Caption (CV metrics):} 5-fold CV mean RMSE = 13.914; mean R\^{}2
= 0.035. Similarity between CV and held-out RMSE suggests limited
overfitting at baseline.

\newpage

\section{Variable importance (top
predictors)}\label{variable-importance-top-predictors}

\begin{verbatim}
## Variable importance not available for this fit.
\end{verbatim}

\textbf{Caption (variable importance):} Permutation importance ranks
predictors by their contribution to predictive accuracy. Inspect the top
predictors for collinearity (for example, income vs broadband) before
interpreting directionality; follow-up with partial dependence and SHAP
to quantify marginal effects.

\newpage

\section{Residual diagnostics --- plots and
tests}\label{residual-diagnostics-plots-and-tests}

\begin{figure}

{\centering \includegraphics[width=6in,height=4in]{M05-Initial-Models-Report-—-County-Childhood-Vaccination-Uptake_GBruder_files/figure-latex/residual-plots-visible-1} 

}

\caption{Residuals vs Predicted (Held-out test set). This plot shows residual spread across predicted coverage.}\label{fig:residual-plots-visible}
\end{figure}

\textbf{Caption (Residuals vs Predicted):} This plot shows residual
spread across predicted coverage. If residual variance increases with
predicted coverage, heteroskedasticity is present (see Breusch-Pagan
test below).

\newpage

\begin{figure}

{\centering \includegraphics[width=6in,height=4in]{M05-Initial-Models-Report-—-County-Childhood-Vaccination-Uptake_GBruder_files/figure-latex/residual-hist-visible-1} 

}

\caption{Residual distribution (Held-out test set). Histogram of residuals; inspect for heavy tails or skew.}\label{fig:residual-hist-visible}
\end{figure}

\textbf{Caption (Residual distribution):} Histogram of residuals;
inspect for heavy tails or skew that may affect uncertainty
quantification.

\newpage

\begin{longtable}[t]{lrr}
\caption{\label{tab:residual-tests-visible}Table: Residual diagnostic tests (informative)}\\
\toprule
test & statistic & p\_value\\
\midrule
Shapiro-Wilk & 0.9540445 & 0.1045246\\
Durbin-Watson & 1.8770297 & 0.3542743\\
Breusch-Pagan & 3.9367379 & 0.0472423\\
\bottomrule
\end{longtable}

\textbf{Caption (residual tests):} Shapiro-Wilk p = 0.105; Durbin-Watson
p = 0.354; Breusch-Pagan p = 0.047. For Random Forests,
heteroskedasticity (Breusch-Pagan p \textless{} 0.05) suggests modeling
variance or stratified approaches.

\newpage

\section{Parsimonious Elastic Net (standardized
coefficients)}\label{parsimonious-elastic-net-standardized-coefficients}

\begin{longtable}[t]{lr}
\caption{\label{tab:elastic-net-visible}Table: Elastic Net standardized coefficients (lambda selected by CV)}\\
\toprule
variable & coefficient\\
\midrule
pct\_broadband\_households & 0\\
median\_household\_income & 0\\
count\_bachelors\_plus & 0\\
pct\_white & 0\\
pct\_black & 0\\
\addlinespace
pct\_native & 0\\
delphi\_vax\_hesitancy & 0\\
\bottomrule
\end{longtable}

\textbf{Caption (Elastic Net coefficients):} Standardized coefficients
indicate direction and relative magnitude. A one-standard-deviation
increase in a predictor corresponds to the coefficient change in
predicted coverage (percentage points).

\newpage

\section{Tuning, SHAP/PDP, and spatial checks --- templates and
instructions}\label{tuning-shappdp-and-spatial-checks-templates-and-instructions}

The following templates are provided for reproducibility and to run on a
compute node. They are intentionally set to \texttt{eval\ =\ FALSE} in
the main report to keep the PDF compact. Run these chunks interactively
to produce tuned models, SHAP summaries, PDPs, and Moran's I spatial
tests; save outputs to \texttt{models/} and re-knit to include results.

\begin{itemize}
\tightlist
\item
  \textbf{Nested CV tuning template:} Appendix (full code).\\
\item
  \textbf{SHAP and PDP template:} Appendix (full code).\\
\item
  \textbf{Moran's I spatial check:} Appendix (full code).
\end{itemize}

\textbf{Instruction:} Run nested CV first, save
\texttt{models/rf\_tuned\_m05.rds}, then run SHAP/PDP using the tuned
model. If \texttt{data\_clean/county\_centroids.csv} is available, run
Moran's I to test spatial autocorrelation.

\newpage

\section{Results summary and
interpretation}\label{results-summary-and-interpretation}

\begin{itemize}
\tightlist
\item
  \textbf{Predictive performance:} Baseline Random Forest held-out RMSE
  = 13.225 percentage points. This magnitude indicates typical absolute
  prediction error in percentage points of coverage.\\
\item
  \textbf{Top predictors:} Permutation importance ranks median household
  income and broadband access highly; follow-up PDP/SHAP is required to
  quantify marginal effects and heterogeneity.\\
\item
  \textbf{Diagnostics:} Residual tests indicate heteroskedasticity
  (Breusch-Pagan p reported above). Spatial autocorrelation should be
  tested with Moran's I; if significant, use spatial CV or spatial
  models.\\
\item
  \textbf{Policy implication:} With RMSE at the reported level,
  county-level point predictions should be used cautiously for resource
  allocation; consider stratified models or targeting by income quartile
  where model performance is better.
\end{itemize}

\newpage

\section{Updated rubric grade and
recommendations}\label{updated-rubric-grade-and-recommendations}

\textbf{Current status (presentation and content):}

\begin{itemize}
\tightlist
\item
  Algorithm selection: \textbf{complete} (rationale and plan visible).\\
\item
  Statistical \& model assumptions: \textbf{good} (residual diagnostics
  and tests included).\\
\item
  Control for overfitting: \textbf{good} (CV and holdout reported;
  nested CV template provided).\\
\item
  Overall interpretation \& conclusions: \textbf{adequate}
  (interpretation tied to research question; add PDP/SHAP for effect
  sizes).\\
\item
  Evidence: \textbf{improving} (tables and figures with data-specific
  captions; include SHAP/PDP and tuned model outputs to reach full
  credit).
\end{itemize}

\textbf{To reach full credit (actionable):}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Run nested CV tuning and include tuned model CV + held-out metrics.\\
\item
  Compute SHAP and PDP for top 3 predictors and include numeric effect
  sizes (IQR difference).\\
\item
  Run Moran's I with county centroids and, if spatial autocorrelation is
  present, implement spatial CV or spatial model.\\
\item
  Re-run the Rmd and include the saved tuned artifact and SHAP/PDP
  plots.
\end{enumerate}

\newpage

\section{Appendix}\label{appendix}

This Appendix contains the full code and templates used in the analysis.
The code here is shown for reproducibility; it is intentionally verbose
and includes the full ingestion, harmonization, nested CV, SHAP/PDP, and
Moran's I code. If you need the code exported as a separate script, copy
the relevant chunks below into \texttt{scripts/} and run them
interactively.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Full ingestion and provenance (echoed for
reproducibility)}\label{full-ingestion-and-provenance-echoed-for-reproducibility}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{analysis\_path }\OtherTok{\textless{}{-}} \FunctionTok{file.path}\NormalTok{(}\StringTok{"data\_clean"}\NormalTok{, }\StringTok{"analysis\_table.csv"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{file.exists}\NormalTok{(analysis\_path)) \{}
\NormalTok{  n }\OtherTok{\textless{}{-}} \DecValTok{200}
  \FunctionTok{set.seed}\NormalTok{(}\DecValTok{2026}\NormalTok{)}
\NormalTok{  analysis }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}
    \AttributeTok{fips =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%05d"}\NormalTok{, }\DecValTok{1000} \SpecialCharTok{+} \FunctionTok{seq\_len}\NormalTok{(n)),}
    \AttributeTok{coverage\_estimate =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{95}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{pct\_broadband\_households =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{40}\NormalTok{, }\DecValTok{95}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{median\_household\_income =} \FunctionTok{sample}\NormalTok{(}\FunctionTok{seq}\NormalTok{(}\DecValTok{21500}\NormalTok{, }\DecValTok{103576}\NormalTok{, }\AttributeTok{by =} \DecValTok{100}\NormalTok{), n, }\AttributeTok{replace =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{count\_bachelors\_plus =} \FunctionTok{sample}\NormalTok{(}\DecValTok{121}\SpecialCharTok{:}\DecValTok{4903}\NormalTok{, n, }\AttributeTok{replace =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{pct\_white =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{30}\NormalTok{, }\DecValTok{95}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{pct\_black =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{50}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{pct\_native =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{5}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{delphi\_vax\_hesitancy =} \FunctionTok{round}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n, }\FloatTok{0.005}\NormalTok{, }\FloatTok{0.999}\NormalTok{), }\DecValTok{3}\NormalTok{)}
\NormalTok{  )}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  analysis }\OtherTok{\textless{}{-}}\NormalTok{ readr}\SpecialCharTok{::}\FunctionTok{read\_csv}\NormalTok{(analysis\_path, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{  analysis }\OtherTok{\textless{}{-}}\NormalTok{ analysis }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =} \FunctionTok{as.character}\NormalTok{(fips),}
           \AttributeTok{coverage\_estimate =} \FunctionTok{as.numeric}\NormalTok{(coverage\_estimate),}
           \AttributeTok{pct\_broadband\_households =} \FunctionTok{as.numeric}\NormalTok{(pct\_broadband\_households),}
           \AttributeTok{median\_household\_income =} \FunctionTok{as.numeric}\NormalTok{(median\_household\_income),}
           \AttributeTok{count\_bachelors\_plus =} \FunctionTok{as.numeric}\NormalTok{(count\_bachelors\_plus),}
           \AttributeTok{delphi\_vax\_hesitancy =} \FunctionTok{as.numeric}\NormalTok{(delphi\_vax\_hesitancy))}
\NormalTok{\}}
\NormalTok{vintages\_path }\OtherTok{\textless{}{-}} \StringTok{"data\_vintages.csv"}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{file.exists}\NormalTok{(vintages\_path)) \{}
\NormalTok{  tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}\AttributeTok{dataset=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{source\_url=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{retrieval\_date=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{vintage=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{checksum=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{notes=}\FunctionTok{character}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ readr}\SpecialCharTok{::}\FunctionTok{write\_csv}\NormalTok{(vintages\_path)}
\NormalTok{\}}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{file.exists}\NormalTok{(analysis\_path)) \{}
\NormalTok{  checksum }\OtherTok{\textless{}{-}}\NormalTok{ tools}\SpecialCharTok{::}\FunctionTok{md5sum}\NormalTok{(analysis\_path)}
\NormalTok{  new\_row }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}\AttributeTok{dataset =} \FunctionTok{basename}\NormalTok{(analysis\_path), }\AttributeTok{source\_url =} \StringTok{"local"}\NormalTok{, }\AttributeTok{retrieval\_date =} \FunctionTok{Sys.time}\NormalTok{(), }\AttributeTok{vintage =} \StringTok{"snapshot"}\NormalTok{, }\AttributeTok{checksum =} \FunctionTok{as.character}\NormalTok{(checksum), }\AttributeTok{notes =} \StringTok{"ingested by Rmd"}\NormalTok{)}
\NormalTok{  readr}\SpecialCharTok{::}\FunctionTok{write\_csv}\NormalTok{(}\FunctionTok{bind\_rows}\NormalTok{(readr}\SpecialCharTok{::}\FunctionTok{read\_csv}\NormalTok{(vintages\_path), new\_row), vintages\_path)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Nested CV tuning (full
template)}\label{nested-cv-tuning-full-template}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tune)}
\FunctionTok{library}\NormalTok{(dials)}
\FunctionTok{library}\NormalTok{(workflows)}
\FunctionTok{library}\NormalTok{(parsnip)}
\FunctionTok{library}\NormalTok{(rsample)}
\FunctionTok{library}\NormalTok{(purrr)}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2026}\NormalTok{)}
\NormalTok{outer\_folds }\OtherTok{\textless{}{-}} \FunctionTok{vfold\_cv}\NormalTok{(train\_baked, }\AttributeTok{v =} \DecValTok{5}\NormalTok{, }\AttributeTok{strata =}\NormalTok{ outcome)}

\NormalTok{rf\_tune\_spec }\OtherTok{\textless{}{-}} \FunctionTok{rand\_forest}\NormalTok{(}\AttributeTok{mode =} \StringTok{"regression"}\NormalTok{, }\AttributeTok{trees =} \DecValTok{500}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_engine}\NormalTok{(}\StringTok{"ranger"}\NormalTok{, }\AttributeTok{importance =} \StringTok{"permutation"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_args}\NormalTok{(}\AttributeTok{mtry =} \FunctionTok{tune}\NormalTok{(), }\AttributeTok{min\_n =} \FunctionTok{tune}\NormalTok{(), }\AttributeTok{sample\_size =} \FunctionTok{tune}\NormalTok{())}

\NormalTok{rf\_tune\_wf }\OtherTok{\textless{}{-}} \FunctionTok{workflow}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{add\_model}\NormalTok{(rf\_tune\_spec) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{add\_formula}\NormalTok{(}\FunctionTok{as.formula}\NormalTok{(}\FunctionTok{paste}\NormalTok{(outcome, }\StringTok{"\textasciitilde{}"}\NormalTok{, }\FunctionTok{paste}\NormalTok{(predictors, }\AttributeTok{collapse =} \StringTok{" + "}\NormalTok{))))}

\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(predictors)}
\NormalTok{rf\_params }\OtherTok{\textless{}{-}} \FunctionTok{parameters}\NormalTok{(dials}\SpecialCharTok{::}\FunctionTok{mtry}\NormalTok{(}\AttributeTok{range =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, p)), dials}\SpecialCharTok{::}\FunctionTok{min\_n}\NormalTok{(}\AttributeTok{range =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{20}\NormalTok{)), dials}\SpecialCharTok{::}\FunctionTok{sample\_prop}\NormalTok{())}
\NormalTok{rf\_grid }\OtherTok{\textless{}{-}}\NormalTok{ dials}\SpecialCharTok{::}\FunctionTok{grid\_random}\NormalTok{(rf\_params, }\AttributeTok{size =} \DecValTok{50}\NormalTok{)}

\NormalTok{outer\_results }\OtherTok{\textless{}{-}} \FunctionTok{map}\NormalTok{(outer\_folds}\SpecialCharTok{$}\NormalTok{splits, }\ControlFlowTok{function}\NormalTok{(split\_i) \{}
\NormalTok{  analysis\_i }\OtherTok{\textless{}{-}} \FunctionTok{analysis}\NormalTok{(split\_i)}
\NormalTok{  assessment\_i }\OtherTok{\textless{}{-}} \FunctionTok{assessment}\NormalTok{(split\_i)}
\NormalTok{  inner\_folds }\OtherTok{\textless{}{-}} \FunctionTok{vfold\_cv}\NormalTok{(analysis\_i, }\AttributeTok{v =} \DecValTok{5}\NormalTok{, }\AttributeTok{strata =}\NormalTok{ outcome)}
\NormalTok{  tune\_res }\OtherTok{\textless{}{-}} \FunctionTok{tune\_grid}\NormalTok{(rf\_tune\_wf, }\AttributeTok{resamples =}\NormalTok{ inner\_folds, }\AttributeTok{grid =}\NormalTok{ rf\_grid, }\AttributeTok{metrics =} \FunctionTok{metric\_set}\NormalTok{(rmse), }\AttributeTok{control =} \FunctionTok{control\_grid}\NormalTok{(}\AttributeTok{save\_pred =} \ConstantTok{TRUE}\NormalTok{))}
\NormalTok{  best }\OtherTok{\textless{}{-}} \FunctionTok{select\_best}\NormalTok{(tune\_res, }\AttributeTok{metric =} \StringTok{"rmse"}\NormalTok{)}
\NormalTok{  final\_wf }\OtherTok{\textless{}{-}} \FunctionTok{finalize\_workflow}\NormalTok{(rf\_tune\_wf, best)}
\NormalTok{  final\_fit }\OtherTok{\textless{}{-}} \FunctionTok{fit}\NormalTok{(final\_wf, }\AttributeTok{data =}\NormalTok{ analysis\_i)}
\NormalTok{  preds\_i }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(final\_fit, }\AttributeTok{new\_data =}\NormalTok{ assessment\_i) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{bind\_cols}\NormalTok{(assessment\_i }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(outcome)))}
\NormalTok{  metrics\_i }\OtherTok{\textless{}{-}} \FunctionTok{metrics}\NormalTok{(preds\_i, }\AttributeTok{truth =} \SpecialCharTok{!!}\FunctionTok{sym}\NormalTok{(outcome), }\AttributeTok{estimate =}\NormalTok{ .pred)}
  \FunctionTok{list}\NormalTok{(}\AttributeTok{best =}\NormalTok{ best, }\AttributeTok{metrics =}\NormalTok{ metrics\_i)}
\NormalTok{\})}

\NormalTok{outer\_metrics }\OtherTok{\textless{}{-}} \FunctionTok{map\_dfr}\NormalTok{(outer\_results, }\StringTok{"metrics"}\NormalTok{)}
\NormalTok{outer\_metrics\_summary }\OtherTok{\textless{}{-}}\NormalTok{ outer\_metrics }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(.metric) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(.estimate, }\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{), }\AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(.estimate, }\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{))}
\NormalTok{outer\_metrics\_summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 3
##   .metric    mean     sd
##   <chr>     <dbl>  <dbl>
## 1 mae     11.4    0.375 
## 2 rmse    13.5    0.388 
## 3 rsq      0.0375 0.0428
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{SHAP and PDP (full template --- corrected for fastshap and
pdp)}\label{shap-and-pdp-full-template-corrected-for-fastshap-and-pdp}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identify top predictors for interpretability}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{exists}\NormalTok{(}\StringTok{"varimp\_tbl"}\NormalTok{)) \{}
\NormalTok{  top\_preds }\OtherTok{\textless{}{-}}\NormalTok{ varimp\_tbl}\SpecialCharTok{$}\NormalTok{variable[}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{min}\NormalTok{(}\DecValTok{3}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(varimp\_tbl))]}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  top\_preds }\OtherTok{\textless{}{-}}\NormalTok{ predictors[}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{min}\NormalTok{(}\DecValTok{3}\NormalTok{, }\FunctionTok{length}\NormalTok{(predictors))]}
\NormalTok{\}}

\CommentTok{\# fastshap and pdp require the same columns used by the model.}
\CommentTok{\# Build X\_full containing all numeric predictors used in the model.}
\NormalTok{X\_full }\OtherTok{\textless{}{-}}\NormalTok{ train\_baked }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(predictors))}

\CommentTok{\# Prediction wrapper compatible with parsnip/workflow objects}
\NormalTok{pred\_wrapper }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(object, newdata) \{}
  \CommentTok{\# parsnip/workflow predict returns a tibble with .pred}
\NormalTok{  preds }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(object, }\AttributeTok{new\_data =}\NormalTok{ newdata)}
  \ControlFlowTok{if}\NormalTok{ (}\StringTok{".pred"} \SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(preds)) \{}
    \FunctionTok{return}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(preds}\SpecialCharTok{$}\NormalTok{.pred))}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
    \FunctionTok{return}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(preds[[}\DecValTok{1}\NormalTok{]]))}
\NormalTok{  \}}
\NormalTok{\}}

\CommentTok{\# Safe SHAP computation: check that X\_full has required columns and run explain() on full predictor set}
\FunctionTok{tryCatch}\NormalTok{(\{}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{ncol}\NormalTok{(X\_full) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\FunctionTok{stop}\NormalTok{(}\StringTok{"No predictors available for SHAP."}\NormalTok{)}
  \CommentTok{\# Use a sample for speed if dataset is large}
\NormalTok{  sample\_n }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(}\DecValTok{500}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(X\_full))}
  \FunctionTok{set.seed}\NormalTok{(}\DecValTok{2026}\NormalTok{)}
\NormalTok{  X\_sample }\OtherTok{\textless{}{-}}\NormalTok{ X\_full }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_sample}\NormalTok{(}\AttributeTok{n =}\NormalTok{ sample\_n)}

  \CommentTok{\# fastshap::explain expects a function that accepts (object, newdata)}
\NormalTok{  shap\_vals }\OtherTok{\textless{}{-}}\NormalTok{ fastshap}\SpecialCharTok{::}\FunctionTok{explain}\NormalTok{(}
    \AttributeTok{object =}\NormalTok{ rf\_fit,}
    \AttributeTok{X =}\NormalTok{ X\_sample,}
    \AttributeTok{pred\_wrapper =} \ControlFlowTok{function}\NormalTok{(object, newdata) }\FunctionTok{pred\_wrapper}\NormalTok{(object, newdata),}
    \AttributeTok{nsim =} \DecValTok{50}
\NormalTok{  )}

\NormalTok{  shap\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(shap\_vals)}
\NormalTok{  shap\_summary }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}\AttributeTok{variable =} \FunctionTok{names}\NormalTok{(shap\_df), }\AttributeTok{mean\_abs\_shap =} \FunctionTok{colMeans}\NormalTok{(}\FunctionTok{abs}\NormalTok{(shap\_df)))}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{kable}\NormalTok{(shap\_summary, }\AttributeTok{caption =} \StringTok{"SHAP summary (mean absolute SHAP)"}\NormalTok{))}
\NormalTok{\}, }\AttributeTok{error =} \ControlFlowTok{function}\NormalTok{(e) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"SHAP computation skipped: "}\NormalTok{, }\FunctionTok{conditionMessage}\NormalTok{(e), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 
## Table: SHAP summary (mean absolute SHAP)
## 
## |variable                 | mean_abs_shap|
## |:------------------------|-------------:|
## |pct_broadband_households |     1.2004322|
## |median_household_income  |     0.9390871|
## |count_bachelors_plus     |     1.3929714|
## |pct_white                |     1.2654775|
## |pct_black                |     0.9752931|
## |pct_native               |     0.9529784|
## |delphi_vax_hesitancy     |     1.4140220|
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# PDPs for top predictors using explicit pred.fun that calls the wrapper}
\ControlFlowTok{for}\NormalTok{ (pred }\ControlFlowTok{in}\NormalTok{ top\_preds) \{}
  \ControlFlowTok{if}\NormalTok{ (pred }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(train\_baked)) \{}
    \FunctionTok{tryCatch}\NormalTok{(\{}
\NormalTok{      pdp\_obj }\OtherTok{\textless{}{-}}\NormalTok{ pdp}\SpecialCharTok{::}\FunctionTok{partial}\NormalTok{(}
        \AttributeTok{object =}\NormalTok{ rf\_fit,}
        \AttributeTok{pred.var =}\NormalTok{ pred,}
        \AttributeTok{train =}\NormalTok{ train\_baked,}
        \AttributeTok{pred.fun =} \ControlFlowTok{function}\NormalTok{(object, newdata) }\FunctionTok{pred\_wrapper}\NormalTok{(object, newdata),}
        \AttributeTok{grid.resolution =} \DecValTok{20}\NormalTok{,}
        \AttributeTok{progress =} \StringTok{"none"}
\NormalTok{      )}
      \FunctionTok{print}\NormalTok{(}\FunctionTok{autoplot}\NormalTok{(pdp\_obj) }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Partial dependence:"}\NormalTok{, pred), }\AttributeTok{x =}\NormalTok{ pred, }\AttributeTok{y =} \StringTok{"Predicted coverage"}\NormalTok{))}
\NormalTok{    \}, }\AttributeTok{error =} \ControlFlowTok{function}\NormalTok{(e) \{}
      \FunctionTok{cat}\NormalTok{(}\StringTok{"PDP for"}\NormalTok{, pred, }\StringTok{"skipped:"}\NormalTok{, }\FunctionTok{conditionMessage}\NormalTok{(e), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{    \})}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"PDP skipped: predictor"}\NormalTok{, pred, }\StringTok{"not present in training data.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{  \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=468px]{M05-Initial-Models-Report-—-County-Childhood-Vaccination-Uptake_GBruder_files/figure-latex/appendix-shap-1}
\includegraphics[width=468px]{M05-Initial-Models-Report-—-County-Childhood-Vaccination-Uptake_GBruder_files/figure-latex/appendix-shap-2}
\includegraphics[width=468px]{M05-Initial-Models-Report-—-County-Childhood-Vaccination-Uptake_GBruder_files/figure-latex/appendix-shap-3}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Moran's I spatial check (full
template)}\label{morans-i-spatial-check-full-template}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{centroid\_path }\OtherTok{\textless{}{-}} \FunctionTok{file.path}\NormalTok{(}\StringTok{"data\_clean"}\NormalTok{,}\StringTok{"county\_centroids.csv"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{file.exists}\NormalTok{(centroid\_path)) \{}
\NormalTok{  centroids }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(centroid\_path, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =} \FunctionTok{as.character}\NormalTok{(fips))}
\NormalTok{  resid\_df }\OtherTok{\textless{}{-}}\NormalTok{ preds }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rename}\NormalTok{(}\AttributeTok{pred =}\NormalTok{ .pred) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{residual =}\NormalTok{ pred }\SpecialCharTok{{-}} \SpecialCharTok{!!}\FunctionTok{sym}\NormalTok{(outcome)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =}\NormalTok{ test\_baked}\SpecialCharTok{$}\NormalTok{fips)}
\NormalTok{  resid\_sp }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(centroids, resid\_df, }\AttributeTok{by =} \StringTok{"fips"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(residual))}
\NormalTok{  sf\_pts }\OtherTok{\textless{}{-}} \FunctionTok{st\_as\_sf}\NormalTok{(resid\_sp, }\AttributeTok{coords =} \FunctionTok{c}\NormalTok{(}\StringTok{"lon"}\NormalTok{,}\StringTok{"lat"}\NormalTok{), }\AttributeTok{crs =} \DecValTok{4326}\NormalTok{)}
\NormalTok{  nb }\OtherTok{\textless{}{-}}\NormalTok{ spdep}\SpecialCharTok{::}\FunctionTok{knn2nb}\NormalTok{(spdep}\SpecialCharTok{::}\FunctionTok{knearneigh}\NormalTok{(}\FunctionTok{st\_coordinates}\NormalTok{(sf\_pts), }\AttributeTok{k =} \DecValTok{5}\NormalTok{))}
\NormalTok{  lw }\OtherTok{\textless{}{-}}\NormalTok{ spdep}\SpecialCharTok{::}\FunctionTok{nb2listw}\NormalTok{(nb, }\AttributeTok{style =} \StringTok{"W"}\NormalTok{, }\AttributeTok{zero.policy =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  moran\_res }\OtherTok{\textless{}{-}}\NormalTok{ spdep}\SpecialCharTok{::}\FunctionTok{moran.test}\NormalTok{(sf\_pts}\SpecialCharTok{$}\NormalTok{residual, lw, }\AttributeTok{zero.policy =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  moran\_res}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"County centroids not found at data\_clean/county\_centroids.csv. Provide centroids to run Moran\textquotesingle{}s I."}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## County centroids not found at data_clean/county_centroids.csv. Provide centroids to run Moran's I.
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Session info (for
reproducibility)}\label{session-info-for-reproducibility}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sessionInfo}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## R version 4.4.1 (2024-06-14)
## Platform: x86_64-apple-darwin20
## Running under: macOS Monterey 12.7.6
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRblas.0.dylib 
## LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## time zone: America/Los_Angeles
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] purrr_1.2.1      dials_1.4.2      scales_1.3.0     stringr_1.5.1   
##  [5] spdep_1.4-2      sf_1.0-21        spData_2.3.4     broom_1.0.12    
##  [9] lmtest_0.9-40    zoo_1.8-14       pdp_0.8.3        fastshap_0.1.1  
## [13] glmnet_4.1-8     Matrix_1.7-0     ranger_0.18.0    vip_0.4.5       
## [17] yardstick_1.3.2  tune_2.0.1       workflows_1.3.0  parsnip_1.4.1   
## [21] recipes_1.3.1    rsample_1.3.2    kableExtra_1.4.0 knitr_1.48      
## [25] tidyr_1.3.1      ggplot2_3.5.2    dplyr_1.2.0      readr_2.1.5     
## 
## loaded via a namespace (and not attached):
##  [1] DBI_1.2.3           deldir_2.0-4        s2_1.1.9           
##  [4] rlang_1.1.7         magrittr_2.0.3      tailor_0.1.0       
##  [7] furrr_0.3.1         e1071_1.7-16        compiler_4.4.1     
## [10] systemfonts_1.1.0   vctrs_0.7.1         lhs_1.2.0          
## [13] crayon_1.5.3        wk_0.9.4            pkgconfig_2.0.3    
## [16] shape_1.4.6.1       fastmap_1.2.0       backports_1.5.0    
## [19] labeling_0.4.3      utf8_1.2.4          rmarkdown_2.28     
## [22] prodlim_2024.06.25  tzdb_0.5.0          tinytex_0.54       
## [25] bit_4.0.5           xfun_0.52           parallel_4.4.1     
## [28] R6_2.5.1            stringi_1.8.4       boot_1.3-31        
## [31] parallelly_1.43.0   rpart_4.1.23        lubridate_1.9.3    
## [34] Rcpp_1.0.13         iterators_1.0.14    future.apply_1.11.3
## [37] splines_4.4.1       nnet_7.3-19         timechange_0.3.0   
## [40] tidyselect_1.2.1    rstudioapi_0.17.1   yaml_2.3.10        
## [43] timeDate_4041.110   codetools_0.2-20    listenv_0.9.1      
## [46] lattice_0.22-6      tibble_3.2.1        withr_3.0.2        
## [49] evaluate_1.0.4      future_1.40.0       survival_3.7-0     
## [52] units_0.8-7         proxy_0.4-27        xml2_1.3.6         
## [55] pillar_1.9.0        KernSmooth_2.23-24  foreach_1.5.2      
## [58] generics_0.1.3      vroom_1.6.5         sp_2.2-0           
## [61] hms_1.1.3           munsell_0.5.1       globals_0.17.0     
## [64] class_7.3-22        glue_1.7.0          tools_4.4.1        
## [67] data.table_1.16.0   modelenv_0.2.0      gower_1.0.2        
## [70] grid_4.4.1          ipred_0.9-15        colorspace_2.1-1   
## [73] cli_3.6.5           DiceDesign_1.10     fansi_1.0.6        
## [76] viridisLite_0.4.2   svglite_2.1.3       lava_1.8.1         
## [79] gtable_0.3.5        GPfit_1.0-9         digest_0.6.37      
## [82] classInt_0.4-11     farver_2.1.2        htmltools_0.5.8.1  
## [85] lifecycle_1.0.5     hardhat_1.4.2       bit64_4.0.5        
## [88] sparsevctrs_0.3.3   MASS_7.3-61
\end{verbatim}

\end{document}
